branch-defaults:
  master:
    environment: django-env
global:
  application_name: my_eb_site
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
