# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [       
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(blank=True, default='', max_length=200)),
                ('customeremail', models.CharField(blank=True, default='', max_length=200)),
                ('customerphone', models.CharField(blank=True, default='', max_length=200)),
                ('customeraddress', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickupdate', models.DateField(blank=True, null=True)),
                ('pickupsize', models.CharField(blank=True, default='', max_length=200)),
                ('pickupprice', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getriddb.Customer')),
            ],
            options={
                'db_table': 'pickup',
            },
        ),    
        migrations.CreateModel(
            name='Inventoryitem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indate', models.DateField(blank=True, null=True)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getriddb.Pickup')),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('segment', models.CharField(blank=True, default='', max_length=200)),
                ('itemtype', models.CharField(blank=True, default='', max_length=200)),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=200)),
                ('firstassessment', models.CharField(blank=True, default='', max_length=200)),
                ('donationvalue', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, default='', max_length=200)),
                ('cut', models.CharField(blank=True, default='', max_length=200)),
                ('style', models.CharField(blank=True, default='', max_length=200)),
                ('fabric', models.CharField(blank=True, default='', max_length=200)),
                ('usecase', models.CharField(blank=True, default='', max_length=200)),
                ('postprice', models.FloatField(blank=True, null=True)),
                ('origprice', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=200)),
                ('statuschangedate', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'inventoryitem',
            },
        ),          
    ]
