# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getriddb.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='pickup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inventoryitems', to='getriddb.Pickup'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='size',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
