# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0002_auto_20170712_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getriddb.Category')),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='segment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='getriddb.Segment'),
            preserve_default=False,
        ),
    ]
