# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0005_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getriddb.Category')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getriddb.Segment')),
            ],
        ),
        migrations.RenameField(
            model_name='color',
            old_name='Color',
            new_name='color',
        ),
    ]
