# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0007_auto_20170712_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutorStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutorstyle', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getriddb.Category')),
                ('itemtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getriddb.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usecase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usecase', models.CharField(max_length=200)),
            ],
        ),
    ]
