# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0008_cutorstyle_fabric_usecase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CutorStyle',
            new_name='Cut',
        ),
        migrations.RenameField(
            model_name='cut',
            old_name='cutorstyle',
            new_name='cut',
        ),
    ]
