# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0009_auto_20170712_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='cut',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
