# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0011_auto_20170719_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='MKTplacefee',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='craigslist',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='customerpayout',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='ebay',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='finalsellingprice',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='itemprofit',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='letgo',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='offerup',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='offline',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='poshmark',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='shippingcosts',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='solddate',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='tradesy',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='up4saledate',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='vinted',
        ),
    ]
