# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0012_auto_20170719_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='statuschangedate',
        ),
    ]
