# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0016_auto_20170719_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='craigslist',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='customerpayout',
            field=models.FloatField(blank=True, help_text='(updated on save)', null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='ebay',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='itemprofit',
            field=models.FloatField(blank=True, help_text='(updated on save)', null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='letgo',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='offerup',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='offline',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='poshmark',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='tradesy',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='vinted',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
