# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0017_auto_20170719_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='cut',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='fabric',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='style',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='usecase',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
