# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0020_auto_20170720_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='(updated on save)'),
        ),
    ]
