# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0027_auto_20170720_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='itemtype',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='segment',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='size',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
