# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0032_auto_20170720_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='itemtype',
        ),
    ]
