# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0033_remove_size_itemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='segment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='getriddb.Segment'),
            preserve_default=False,
        ),
    ]
