# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0037_auto_20170720_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_MKTplacefee',
            new_name='MKTplacefee',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_craigslist',
            new_name='craigslist',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_ebay',
            new_name='ebay',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='itemprofit',
            new_name='item_profit',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_letgo',
            new_name='letgo',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_offerup',
            new_name='offerup',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_offline',
            new_name='offline',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_poshmark',
            new_name='poshmark',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_shippingcosts',
            new_name='shippingcosts',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_tradesy',
            new_name='tradesy',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_vinted',
            new_name='vinted',
        ),
    ]
