# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0039_auto_20170724_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getriddb.Category', to_field='category'),
        ),
    ]
