# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0040_auto_20170725_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='colors',
            field=models.ManyToManyField(to='getriddb.Color'),
        ),
    ]
