# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0041_inventoryitem_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='cuts',
            field=models.ManyToManyField(to='getriddb.Cut'),
        ),
    ]
