# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0042_inventoryitem_cuts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cut',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='segment',
        ),
    ]
