# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0045_auto_20170727_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricPercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.CharField(max_length=40)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getriddb.Fabric')),
                ('inventoryitemkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getriddb.Inventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='fabrics',
            field=models.ManyToManyField(to='getriddb.FabricPercent'),
        ),
    ]
