# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0046_auto_20170727_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
