# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getriddb', '0048_customer_last_pickup_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paydate', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(blank=True, default='', max_length=200)),
                ('customerpaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getriddb.Customer')),
            ],
            options={
                'db_table': 'customerpayout',
            },
        ),
    ]
